### ISSUE TITLE
GAMA DAYS 2024 Website To Do List

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.resources#7]
Website sources (https://github.com/gama-platform/gama.resources/tree/main/conferences/Gama-Days-2024)
- [x] Modify the 2022 website to 2024
- [x] Host the website online: @RoiArthurB is it possible to host it on the Gama Platform Website to have this adress https://gama-platform.org/gama-days-2024 ? 
- [ ] Create a conference on easy chair (WIP)
- [ ] Link to the good mailing list (replace mailto:gamadays2024@easychair.org by mailto:gamadays2024@easychair.org)
- [x] Create a google doc register form => https://forms.gle/jJ41xed5TYoW9MyD9
- [ ]  Update index.html

**Comment by RoiArthurB** [comment]
>     * [ ]  Host the website online: @RoiArthurB is it possible to host it on the Gama Platform Website to have this adress https://gama-platform.org/gama-days-2024 ?

@agrignard Just create a repository in the organisation called `gama-days-2024` and the Github Pages will automatically point to that URL :)

**Comment by agrignard** [comment]
Ok to the new repo is created with the hmtl/js code at the root
https://github.com/gama-platform/gama-days-2024

@RoiArthurB do I need to do something else? The Github actions are automatically triggered? will it have this url https://gama-platform.org/gama-days-2024 ?

As soon as it's operational I will move the issue related to the website to this repo (later we will rearchive it in the gama.ressources)

**Comment by RoiArthurB** [comment]
> @RoiArthurB do I need to do something else? The Github actions are automatically triggered? will it have this url https://gama-platform.org/gama-days-2024 ?

Everything is set up, the website will be automatically updated on each commit. Nothing more to worry about ;)

**Comment by agrignard** [comment]
Thanks @RoiArthurB I close this issue (to open new one in the dedicated repo ;-)
